### ISSUE TITLE
Trying to edit a milestone doesn't work

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#1034]
https://beta.giveth.io/campaigns/5d110631994eac53adc8f21e/milestones/5d7fd9dfad3696263686cc1b/edit

Don can't even get to that screen... I can (as the campaign manager), but when i go to edit the text it fails:
<img width="1091" alt="Screen Shot 2019-10-17 at 9 34 06 AM" src="https://user-images.githubusercontent.com/14945613/66973164-52cc8400-f0c1-11e9-939a-48ceadf75642.png">

My wallet is unlocked and so was Don's

**Comment by arbreton** [comment]
Seems to be this allowance problems are on the rise, and we still haven't found a root cause why allowance is a problem or why it is not interacting correctly with the contract

**Comment by krrisis** [comment]
I currently cannot my Milestone either. 

I hit 'edit' (works), put in the correct text (works), but when I want to hit 'Update Milestone' (which is green, not greyed out!) nothing happens.

I have this issue for [this Milestone](https://beta.giveth.io/campaigns/5d110631994eac53adc8f21e/milestones/5df00afa71e84069aad0a228) and I hope it can be fixed urgently bcs I need to get to these funds.. Thank you!

**Comment by aminlatifi** [comment]
> I currently cannot my Milestone either.
> 
> I hit 'edit' (works), put in the correct text (works), but when I want to hit 'Update Milestone' (which is green, not greyed out!) nothing happens.
> 
> I have this issue for [this Milestone](https://beta.giveth.io/campaigns/5d110631994eac53adc8f21e/milestones/5df00afa71e84069aad0a228) and I hope it can be fixed urgently bcs I need to get to these funds.. Thank you!

https://github.com/Giveth/giveth-dapp/blob/f04d827813787ac386832cca6c69b72c72a761c3/src/services/MilestoneService.js#L401-L403

@arbreton This condition doesn't allow to patch milestone after updating! This is reached when milestone status is not proposed or rejected like the milestone mentioned here. I don't know why we save milestones in IPFS? do you know?
However removing the condition could solve the problem.

**Comment by arbreton** [comment]
We can definitely replace this condition and see if it gets fixed

**Comment by arbreton** [comment]
Told me you had checked this one a little, assigning the issue to you @aminlatifi

**Comment by krrisis** [comment]
hey @aminlatifi could you let me know how much time you think this issue will take? If this takes a few days I prefer remaking my Milestone and cancelling this one, because I need to pay my bills.. :/ thanks!

**Comment by aminlatifi** [comment]
> hey @aminlatifi could you let me know how much time you think this issue will take? If this takes a few days I prefer remaking my Milestone and cancelling this one, because I need to pay my bills.. :/ thanks!

@krrisis I applied a hotfix, it would solve editing issue.

**Comment by krrisis** [comment]
hey amin, great news.. is that hotfix already live? If so it unfortunately did not fix the issue... 
Below you can find the error that pops up in the console when I hit that button.
What I do see now in the Milestone (after reading that error) is that the currency for some reason says 'AUD'. Could that be part of the issue?  

CONSOLE message: 

main.b57be8a8.js:1 Uncaught TypeError: The type of conversionRate supplied to t is: undefined. Expected one of: number.
    at t.value (main.b57be8a8.js:1)
    at t.set (main.b57be8a8.js:1)
    at t.value (main.b57be8a8.js:1)
    at n.submit (main.b57be8a8.js:1)
    at Object.<anonymous> (main.b57be8a8.js:1)
    at w (main.b57be8a8.js:1)
    at main.b57be8a8.js:1
    at x (main.b57be8a8.js:1)
    at C (main.b57be8a8.js:1)
    at A (main.b57be8a8.js:1)

**Comment by aminlatifi** [comment]
> hey amin, great news.. is that hotfix already live? If so it unfortunately did not fix the issue...
> Below you can find the error that pops up in the console when I hit that button.
> What I do see now in the Milestone (after reading that error) is that the currency for some reason says 'AUD'. Could that be part of the issue?
> 
> CONSOLE message:
> 
> main.b57be8a8.js:1 Uncaught TypeError: The type of conversionRate supplied to t is: undefined. Expected one of: number.
> at t.value (main.b57be8a8.js:1)
> at t.set (main.b57be8a8.js:1)
> at t.value (main.b57be8a8.js:1)
> at n.submit (main.b57be8a8.js:1)
> at Object. (main.b57be8a8.js:1)
> at w (main.b57be8a8.js:1)
> at main.b57be8a8.js:1
> at x (main.b57be8a8.js:1)
> at C (main.b57be8a8.js:1)
> at A (main.b57be8a8.js:1)

@krrisis I merged changes to master branch, so I hope it be applied automatically. If not, we should wait until @arbreton develop new version.
I myself is not whitelisted to test similar scenario on beta. But I could do in my local version and it worked.

**Comment by krrisis** [comment]
I didn't comment back bcs I wanted to see if @arbreton could confirm but nope.. it's indeed not yet working. Will see if griff could fill a new Milestone, because I'm getting refused bank cards again..

**Comment by aminlatifi** [comment]
> I didn't comment back bcs I wanted to see if @arbreton could confirm but nope.. it's indeed not yet working. Will see if griff could fill a new Milestone, because I'm getting refused bank cards again..

I am waiting till @arbreton add me to whitelist to test and debug on beta. I can edit milestone successfully on localhost, so I need to test on beta to find and fix the bug.

**Comment by krrisis** [comment]
ok, so just FYI, cancelled the above Milestone, so our (limited) funds can flow back to the Campaign. Could still not edit though.
