### ISSUE TITLE
Trying to "mark complete" to my milestone after it was funded

### ISSUE THREAD

**Issue by macguyvar** [Giveth/giveth-dapp#923]
Issue type: **Error**
Something went wrong with the transaction.

**TransactionLink:**
https://rinkeby.etherscan.io/tx/undefined => {}

**Comment by arbreton** [comment]
Thank you for reporting @macguyvar , can you try again? it should be working now!

**Comment by macguyvar** [comment]
still getting the error message

**Comment by arbreton** [comment]
Is there any chance you can screenshot the developer console on your browser?, have you tried clearing cache? please keep me posted!

**Comment by macguyvar** [comment]
cleared cache still not working.  
![Capture](https://user-images.githubusercontent.com/34863064/62329064-a8ea3d80-b469-11e9-839b-16af19752d9a.JPG)
![Capture1](https://user-images.githubusercontent.com/34863064/62329077-b43d6900-b469-11e9-95ee-bdd5a41eb844.JPG)

**Comment by macguyvar** [comment]
is it because im on the rinkeby test network?

**Comment by arbreton** [comment]
That should be the correct network for marking complete a milestone, are you on google chrome or chrominium variant @macguyvar ? 
if so try this and mark complete you should see the console like this one
<img width="580" alt="Screen Shot 2019-08-01 at 2 40 51 PM" src="https://user-images.githubusercontent.com/12836187/62329390-9de3dd00-b46a-11e9-920b-1e1752d9cf6b.png">
<img width="1438" alt="Screen Shot 2019-08-01 at 2 42 11 PM" src="https://user-images.githubusercontent.com/12836187/62329395-9fada080-b46a-11e9-8ce1-0a6f3c14417c.png">

**Comment by arbreton** [comment]
There should be an error on the console when marking complete

**Comment by macguyvar** [comment]
![Capture](https://user-images.githubusercontent.com/34863064/62329705-82c59d00-b46b-11e9-9289-dd3bfd15e531.JPG)

**Comment by macguyvar** [comment]
something about gas requirements

**Comment by arbreton** [comment]
Thank you very much @macguyvar!, seems related, let me investigate further, i will get back to you asap

**Comment by arbreton** [comment]
There is something wrong with the gas calculator at this point, this might be due to the high activity on ETH right-now, 

I'm still investigating but in the meantime if you can try in Metamask before making the transaction click on the **gas cost**, 

Under the gas limit input **700 000 max** limit, that should be a safe gas limit, right now for some reason is calculating 7 million

**Comment by macguyvar** [comment]
Where do I adjust the gas cost? When I mark complete the error message comes up. There is no interaction with meta mask before I get the error.

**Comment by arbreton** [comment]
I see, I will need to do the necessary adjustments asap

**Comment by arbreton** [comment]
@macguyvar, after in depth investigation what happened was that the transaction for requestReview went through successfully!

But yesterday with the faucet problem actually caused to take your milestone out of sync, 

Now it's synced with the chain, and it's ready for @Danibelle to review!
