### ISSUE TITLE
Milestone 'overfilled' although capped 

### ISSUE THREAD

**Issue by krrisis** [Giveth/giveth-dapp#996]
Feathers has sent the same amount multiple times to [this Milestone](https://beta.giveth.io/campaigns/5d110631994eac53adc8f21e/milestones/5d829497ad3696263686cc6d), and only needed to send it once as you can see below. (more context under this) : 

![image](https://user-images.githubusercontent.com/6533925/65391485-116ae200-dd6a-11e9-94c6-9fc8a420e6e5.png)

Got donated kinda endlessly as you can see below and in the Milestone. Will complete now and see if the funds are returned.

![image](https://user-images.githubusercontent.com/6533925/65391507-50009c80-dd6a-11e9-9e91-b9984bfc224d.png)

**Comment by arbreton** [comment]
@krrisis i have never seen anything like this before, how this happened?!, it's super strange indeed, i will check in depth how this happened exactly !, even though this gets repeated, it's an error on feathers but the txHash is the same so at the time of collecting only 1 donation will count, for now i fixed the milestone

**Comment by krrisis** [comment]
hey andre, thx for this. No idea how this happened, griff only filled the Milestone once. 
So in the Milestone I still see the wrong total amount donated, do you mean that you fixed it in the backend? Just want to make sure I can disburse it after review or if I should wait.

**Comment by arbreton** [comment]
Sorry for that @krrisis, i removed the duplicates on the donations, the total amount was missing, now it should be all corrected back to normal!, will replicate, thank you alot for this insight

**Comment by GriffGreen** [comment]
Hey @arbreton is this also affecting the available delegations for the campaign? I am surprised we ran out of money in the Campaign already.

**Comment by lorelei1** [comment]
I'm encountering this issue again with Adam's milestone: https://beta.giveth.io/campaigns/5d110631994eac53adc8f21e/milestones/5d55cfe0ded7183fafb04956 
<img width="682" alt="Screen Shot 2019-12-04 at 2 14 58 PM" src="https://user-images.githubusercontent.com/38163206/70121309-e6bdd380-16a0-11ea-9561-ea9d9fd9293c.png">

**Comment by krrisis** [comment]
and we're having this again in this one cc @Danibelle 

https://beta.giveth.io/campaigns/5cb61c74ef66237670c4ee33/milestones/5e4c2a3911b6b12e5cfbad78

**Comment by arbreton** [comment]
WIP at #1029
